esphome:
  name: dif-pressure-meter

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:
  # baud_rate: 0

# api:

# ota:
#   password: !secret ota_password

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

debug:
  update_interval: 2s

sensor:
  - platform: debug
    loop_time:
      id: loop_time
      name: "Loop Time"

  - platform: uptime
    id: uptime_sensor
    name: Uptime Sensor
    update_interval: 0.1s
    accuracy_decimals: 2

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  interface: hardware

# Example configuration entry
display:
  - platform: st7735
    id: my_display
    model: "INITR_18BLACKTAB"
    reset_pin: GPIO4
    cs_pin: GPIO5
    dc_pin: GPIO2
    rotation: 180
    device_width: 128
    device_height: 160
    col_start: 0
    row_start: 0
    eight_bit_color: true
    update_interval: 0.25s
    data_rate: 80MHz

    pages:
      - id: page1
        lambda: |-
          // Draw the graph at position [x=10,y=20]
          it.print(0, 10, id(font_roboto), id(my_blue), "Hello World!");
          it.printf(0, 30, id(font_roboto), "Uptime: %.2f s", id(uptime_sensor).state);
          it.printf(0, 50, id(font_roboto), id(my_red), "Loop: %.1f ms", id(loop_time).state);
      - id: page2
        lambda: |-
          it.printf(0, 10, id(font_roboto), id(my_red), "Loop: %.1f ms", id(loop_time).state);
          it.graph(10, 30, id(uptime_graph));

interval:
  - interval: 5s
    then:
      - display.page.show_next: my_display
      - component.update: my_display

graph:
  # Show bare-minimum auto-ranged graph
  - id: uptime_graph
    duration: 5min
    width: 108
    height: 51
    x_grid: 1min
    traces:
      - sensor: uptime_sensor
        line_type: SOLID
        line_thickness: 4
        color: my_red

color:
  - id: my_blue
    blue: 100%
  - id: my_red
    red: 100%
  - id: my_green
    green: 100%
  - id: my_white
    red: 100%
    blue: 100%
    green: 100%
  # - id: my_yellow
  #   hex: ffff00
    
font:
  - file: "gfonts://Roboto"
    id: font_roboto
    size: 15
