M48
; DRILL file {KiCad 7.0.7} date Sun Oct 29 22:41:16 2023
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-10-29T22:41:16+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.7
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X143.395Y-74.11
X143.395Y-79.89
T2
X112.2Y-113.1
X146.3Y-113.1
T0
M30
