---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:

jobs:
  ci:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
    outputs:
      esphome-version: ${{ steps.esphome-build.outputs.esphome-version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: "pip"

      - id: cache
        name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.platformio
          key: ${{ runner.os }}-${{ matrix.python-version }}

      - name: Install requirements
        run: |
          pip install -r requirements.txt

      - name: Run yamllint
        run: |
          yamllint $(git ls-files '*.yaml')

      - name: Run pylint
        run: |
          pylint $(git ls-files '*.py')

      - name: Run clang-format
        run: |
          clang-format-13 --dry-run --Werror $(git ls-files '*.cpp' '*.h')

      - name: Compile
        run: |
          esphome compile dif-pressure-meter.yaml

      - name: Official build action
        uses: esphome/build-action@v1.5.2
        id: esphome-build
        with:
          yaml_file: dif-pressure-meter.yaml
          version: "2023.10.6"

      - name: "Move files"
        run: |
          mkdir output
          mv "${{ steps.esphome-build.outputs.name }}" output/

      - name: "Upload"
        uses: actions/upload-artifact@v3.1.2
        with:
          name: dif-pressure-meter
          path: output
